### ISSUE TITLE
compiling this isn't straightforward

### ISSUE THREAD

**Issue by naikrovek** [philburr/atsc#4]
Hi, thank you for this tool.

I'm not able to compile it, even though I know how to use `cmake` and I have cloned with `--recursive`.  

I think the version of Catch2 that you're using is out of date, as I get compile errors from it.  When I search for that error on the Catch2 repo, I find [an issue](https://github.com/catchorg/Catch2/issues/2421) mentioning that it is fixed in a later v2 release, so I replaced the submodule with the latest v2 Catch2 release.  I got further, but now I get unused variable errors for variables which are definitely used (because I get "use of undeclared identifier" errors when I comment them out.)

I've tried with both `gcc` and `clang`/`clang++` and I don't know C++ well enough to fix these.

**Comment by naikrovek** [comment]
Following the azure build yaml also doesn't seem to work.  I thought gcc-8 may have been required, but it gives the same errors.  I'm out of ideas.

**Comment by philburr** [comment]
I have a build that fixes these issues. I will push it out today.

**Comment by naikrovek** [comment]
You did it, thank you so very much!

**Comment by naikrovek** [comment]
Man, I need to get a better computer.  Or try doing this on one of my better computers.  ATSC is CPU intensive, apparently. :smile:  

I knew it was, but I thought something written in C would work on that computer.

Thanks again.  Issue resolved, so closing.  You're my hero.
